---
title: 'Lab 5: Independence and Screening'
author: 'Name and Student ID'
data: "Today's Date"
output: pdf_document
---
### Instructions

Part 1 of this lab focuses on calculating probability of independent events.

### Section I: Breakout Problems on Independence

## Blood Type

**Question 1. From Baldi and Moore (3E question 10.28, 4E question 10.30)**

All human blood can be one of the following types: O, A, B, or AB, but the distribution of types varies a bit among groups of people. Here are the distributions of blood types for a randomly chosen person in China and in the United States:

Check out the following table:

|       |  $O$ |  $A$ |  $B$ |  $AB$ | 
|-------|------|------|------|-------|
|China  |  0.35|  0.27|  0.26|   0.12| 
|U.S.   |  0.45|  0.40|  0.11|   0.04|   

Choose an American and a Chinese person at random, independently of each other.

**1.a	What is the probability that both have type O blood?**

Replace with your answer.


**1.b	What is the probability that both have the same blood type?**


Replace with your answer.


**Question 2. From Baldi and Moore (3E question 10.29, 4E not present)**

_Universal blood donors._

People with type O-negative blood are universal donors. That is, any patient can receive a transfusion of type O-negative blood. Only 7.2 % of the American population have O-negative blood. If 10 people appear at random to give blood, what is the probability that at least  1  of them is a universal donor?

Replace with your answer.


**Question 3. From Baldi and Moore (3E question 10.46, 4E not present)**

_Mendelian inheritance._ 

Some traits of plants and animals depend on inheritance of a single gene. This is called _Mendelian inheritance_, after Gregor Mendel (1822-1884). Each of us has an ABO blood type, which describes whether two characteristics called A and B are present. Every human being has two blood type alleles (gene forms), one inherited from our mother and one from our father. Each of these alleles can be A, B, or O.  Which two we inherit determines our blood type. Here is a table that shows what our blood type is for each combination of two alleles.

|Alleles inherited   | 	Blood type|
|--------------------|------------|
|	A and A            |           A|
|	A and B	           |			    AB|
|	A and O	           |			     A|
|	B and B	           |           B|
|	B and O	           |		    	 B|
|	O and O	           |     			 O|

We inherent each of a parent’s two alleles with probability .50, and we inherit independently from our mother and our father.

Punnett squares are used in genetics courses to organize these sorts of information. The alleles for one parent label the row and for the other parent label the columns.


**3.a Rachel and Jonathan both have alleles A and B. What blood types can their children have?**

Fill in the Punnett Square.

|			  |		|Jonathan |
|-------|---|----|----|
|       |   |  A |  B |
|Rachel	| A	|	   |    |
|       | B	|	   |    |
          
          
**3.b Jasmine has alleles A and O. Tyrone has alleles B and O.  What is the probability that a child of these parents has blood type O?**

Replace with your answer.


_The next calculations assume that they do not have any twins or triplets,so that each child is independent_
 
**3.c If Jasmine and Tyrone have three children, what is the probability that all three have blood type O?	What is the probability that the first child has blood type O and the next two do not?**

Replace with your answer.

**What is the probability that the first child has blood type O and the next two do not?**
             
Replace with your answer.

## The Flu

**Question 4. From Baldi and Moore (2E question 10.20 to 10.23)**

The November 2009 Gallup-Healthways Well-Being Index survey asked a random sample of 28,606 American adults whether they had the flu on the day before the interview.  Here are the results by age group:

|age group |		flu| 		no flu|	  total|
|----------|-------|----------|--------|
| 18 to 29 |		 88|	   2,486|   2,574|
|	30 to 44 |		132|	   5,162|   5,294|
|	45 to 64 |		276|		11,733|  12,009|
|	65+      |	  122|	   8,607|	  8,729|
|total     |	  618|		27,988|  28,606|

The events  "adult is in a specified age group" and "adult has the flu" are called **independent** if the probability of flu does not vary across the age groups.

The conditional probabilities of flu among those age 65 and older: __Replace with your answer__ and flu among those 18 to 29 years old __Replace with your answer__. 

Compare the probability of flu among those age 65 and older and the probability of flu among those 18 to 29 years old. What conclusions can you make about the variation in flu by age group?

Replace with your answer.


This shows that the events "age group" and "adult has the flu" are **not** independent.
Another way to check for independence is to see if the overall probability of flu differs from the age-group stratum specific probabilities of flu. Calculate the overall probability of flu below. Is it the same as the age-group specific probabilities?

Replace with your answer.


### Section II: Screening

We will talk about a very important use of conditional probability in public 
health and medicine, which is the idea of tools that screen for health outcomes.
There are many examples of this, including mammograms for detection of breast 
cancer, the prostate specific antigen (PSA) for detection of prostate cancer, as 
well as tests for exposure to infectious diseases, and so forth.  We will 
consider two types of events: i) whether the subject truly has the health condition
of interest (let $D$ denote the disease of interest, and $D'$ its complement), 
and ii) whether a test was positive or not for this outcome (let $+$ denote a 
positive test and $-$ denote its complement, a negative test). There are several 
statistics that are used to evaluate the performance of a test, some of which 
are derivable from each other:

- Sensitivity: $P(+ \mid D)$ or the probability of test being positive if one 
has the disease.
- Specificity: $P(- \mid D')$ or the probability of test being negative given 
one does not have the disease. 
- Positive predictive value (PPV): $P(D \mid +)$ or the probability of having the 
disease if an individual tests positive.
- Negative predictive value (NPV):  $P(D' \mid -)$ or the probability of not having the 
disease if an individual tests negative.

Consider the following situation: Assume the total number of subjects is 10,000
and that, $P(D) = 0.05$, $P(+ \mid D) = 0.95$, $P(- \mid D') = 0.95$. This set up
implies that the disease is rare, but that a very accurate test exists (i.e., 
equally high sensitivity and specificity).

1. Fill in the following  two-way table with the absolute frequencies using the 
information provided in the problem. (You can fill it in simply by typing the 
frequencies in the nine empty cells.):

|       | $D$ | $D'$ |  Total|
|-------|-----|------|-------|
|+      |     |      |       |
|-      |     |      |       |
| Total |     |      |       |


2. Calculate the PPV using the table.

Replace with your answer.
  
  
3. Re-do the two-way table and re-calculate the PPV, this time assuming that 
$P(D)=0.02$. (Note that $P(+ \mid D) = 0.95$, $P(- \mid D') = 0.95$, as with 
the previous question.)  
  
Replace this text with your calculations
    
    
|       | $D$ | $D'$ |  Total|
|-------|-----|------|-------|
|+      |     |      |       |
|-      |     |      |       |
| Total |     |      |       |
  
  
  
4. Explain why the sensitivity is so high, but the PPV is low for the first 
calculation and even lower for the second calculation.
  
Replace with your answer.

## Testing for HIV.

**Question 5. From Baldi and Moore (question 10.14)**


Enzyme immunoassay tests are used to screen blood specimens for the
presence of antibodies to HIV, the virus that causes AIDS. Antibodies indicate the presence of
the virus. The test is quite accurate but is not always correct. Here are approximate
probabilities of positive and negative test results when the blood tested does and does not
actually contain antibodies to HIV. [Hint: these are conditional probabilities, given HIV status.]

* P( test positive + | antibodies present ) = 0.9985
* P( test positive + | antibodies absent ) = 0.0060
* P( test negative – | antibodies present ) = 0.0015
* P( test negative – | antibodies absent ) = 0.9940

Suppose that 1% of a large population carries antibodies to HIV in its blood.

**5.a On a piece of scratch paper, draw a tree diagram representing the HIV status if a person from this population (outcomes: antibodies present or absent) and the blood test result (outcomes: test positive or test negative). **



**5.b Using your tree diagram, what is the probability that the test is positive for a randomly chosen person from this population?**

Replace with your answer.


**Question 6. From Baldi and Moore (10.16)**

Continue your work and probability assumptions from Question 5.

**6.a What is the probability that a person has the antibody, given that the test is positive.  Explain in your own words what this means.**


Replace with your answer.


**6.b. Identify the test's sensitivity, specificity, and positive predictive value.**


Sensitivity: _your answer here_
Specificity: _your answer here_
Positive Predictive Value: _your answer here_


**Question 7. According to the CDC's Behavioral Risk Factor Surveillance System (BRFSS) about 60% of American adults live a sedentary lifestyle.**


**Noting that random sampling gives us independent observations, you randomly select 10 adults from this population.  Find the following probabilities:**


**7.a All 10 have a sedentary lifestyle**

Replace with your answer.

**7.b At least one does not have a sedentary lifestyle**

Replace with your answer.
 


**Submission** 

Please submit your lab *directly* to 
Gradescope. You can do this by knitting your file and downloading the PDF to 
your computer. Then navigate to Gradescope.com to submit your assignment. Here 
is a tutorial if you need help: https://www.gradescope.com/get_started. 
Scroll down on that page to "For students:submitting homework".